security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_USER:  ROLE_USER

    providers:
        in_memory:
           memory:
              users:
                  admin: { password: password, roles: 'ROLE_ADMIN' }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        in_memory:
            pattern:    ^/
            anonymous: ~

    access_control:
